module.exports = [
  "You look like you're going to spend your life having one epiphany after another, always thinking you've finally figured out what's holding you back, and how you can finally be productive and creative and turn you life around. But nothing will ever change. That cycle of mediocrity isn't due to some obstacle. It's who you are. The thing standing in the way of your dreams is that the person having them is you.",
  "I hope you realize everyone's just putting up with you.",
  "If I was locked in a room with Stalin, Hitler, and you, and had a gun with only 2 bullets, I'd shoot you twice.",
  "Somewhere out there is a tree, tirelessly producing oxygen so you can breathe. I think you owe it an apology.",
  "I don't have the time nor crayons to explain this on your level.",
  "I wish we were better strangers.",
  "Your mother was a hamster and your father smells of elderberries.",
  "It looks like your face caught fire and someone tried to put it out with a bicycle chain.",
  "Your IQ doesn't make a respectable earthquake.",
  "Your mom's so fat that her Patronus is a cake.",
  "Isn't it rather dangerous to use one's entire vocabulary in a single sentence?",
  "You should eat some of your make up so you can be pretty on the inside.",
  "I'm jealous of people that don't know you!",
  "A nerd is at least smart.",
  "So a thought crossed your mind? Must have been a long and dangerous journey.",
  "It's scary to think that people like you are allowed to vote.",
  "Don't let your mind wander. It's too small to be out there on its own.",
  "I don't hate you, but if you were on fire and I had water, I'd drink it.",
  "If I wanted to kill myself, I'd climb to your ego and jump to your IQ.",
  "You are at the top of the bell curve.",
  "Well I could agree with you, but then we'd both be wrong.",
  "If you spoke your find, you'd be speechless.",
  "It's better to let someone think you are an idiot than to open your mouth and prove it.",
  "I hope the rest of your day is as pleasant as you are.",
  "Did you fall from heaven? Cause you face is messed up!",
  "You're the personificiation of Comic Sans.",
  "You're the reason they only have McRibs a certain time of the year. :(",
  "You are so stupid, you'd trip over a cordless phone.",
  "If you're gonna be a smartass, first you have to be smart. Otherwise you're just an ass.",
  "I'll never forget the first time we met, although I'll keep trying.",
  "So you've changed your mind, does this one work any better?",
  "I heard you went to a haunted house and they offered you a job.",
  "You stare at frozen juice cans because they say, 'concentrate'.",
  "I don't know what makes you so stupid, but it really works!",
  "Aww, it's so cute when you try to talk about things you don't understand.",
  "You have the perfect face for radio.",
  "If brains were dynamite you wouldn't have enough to blow your nose.",
  "I've seen people like you, but I had to pay admission!",
  "Brains aren't everything. In your case they're nothing.",
  "You must be the arithmetic man; you add trouble, subtract pleasure, divide attention, and multiply ignorance.",
  "I love what you've done with your hair. How do you get it to come out of the nostrils like that?",
  "I'd like to help you out. Which way did you come in?",
  "You must think you're strong, but you only smell strong.",
  "If you are going to be two faced, at least make one of them pretty.",
  "You're so stupid you tried to wake a sleeping bag.",
  "You shouldn't play hide and seek, no one would look for you.",
  "You have a very sympathetic face. It has everyone's sympathy.",
  "Do you even have a demo for this week?",
  "Why doesn't your website use any Bootstrap?",
  "You're so ugly, the only dates you get are on a calendar.",
  "If you had another brain, it would be lonely.",
  "You're not exactly bad looking. There's just one little problem between your ears - your face!",
  "Looks aren't everything; in your case, they aren't anything!",
  "You must be on the seafood diet. When you see food, you eat it!",
  "Yeah, you're pretty stupid.",
  "You are so incomprehensibly stupid, I am honestly baffled that you somehow have managed to go this long without forgetting how to breathe.",
  "You are living proof that natural selection doesn't always work. Statistically speaking, you should have been eaten by wolves over a decade ago.",
  "I hope you step on a Lego.",
  "I bite my thumb at you.",
  "I hope you are brought to the top of a cliff by the person you love most in the world, and they push you off. And as you accept your mortality and make peace with it, the instant before you hit the ground, Superman comes out of nowhere and saves you. He then flies into the air, and drops you from even higher.",
  "I refuse to have a battle of wits with an unarmed man."
];
